version: "3"

services:
  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VARIANT=3.12
    volumes:
      - ../:/workspace/
    tty: true

  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      AWS_REGION: ap-northeast-1
