name: ci

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2

      - name: Setup Python 🔧
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64

      - name: Python Install dependencies 🧹
        run: |
          pip3 install -r requirements-dev.txt

      - name: Run linter 👀
        run: flake8

      - name: Run test 🧪
        run: pytest -s tests
