name: docker-hub-release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # <= https://github.com/actions/checkout/issues/265
      - run: git checkout ${{ github.event.inputs.ref }}
        if: ${{ github.event.inputs.ref != '' }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: danishi/dynamodb-csv

      - name: Log in to Docker Hub 🚪
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub 🎁
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
