name: reviewdog

on: [pull_request]

jobs:
  flake8-lint:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }} 🔧
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run linter 👀
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning

      - name: Python Install dependencies 🧹
        run: |
          pip3 install -r requirements-dev.txt

      - name: Run unit tests 🧪
        run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Lizard 🌀
        uses: Uno-Takashi/Lizard-Runner@v3
        with:
          path: "./app ./tests"
          CCN: "20"
          arguments: "10"
          ignore_warnings: "2"
